ServerEvents.recipes(event => {
  event.remove({ output: 'chancecubes:chance_cube' })
  event.remove({ output: 'waystones:deepslate_waystone' })
  event.remove({ output: 'waystones:waystone' })
  event.remove({ output: 'waystones:sandy_waystone' })
  event.remove({ output: 'waystones:mossy_waystone' })
  event.remove({ output: 'waystones:blackstone_waystone' })
  event.remove({ output: 'waystones:end_stone_waystone' })
  event.remove({ output: 'waystones:portstone' })
  event.remove({ output: 'waystones:sharestone' })
  event.remove({ output: 'waystones:warp_stone' })
  event.remove({ output: 'waystones:white_sharestone' })
  event.remove({ output: 'cataclysm:infernal_forge' })
})