#Item that can be used to reforge any item.
"Global reforger" = "minecraft:nether_star"
#List of items that cannot get qualities.
"Black list" = []
#Overrides reforging requirements. Format: item_or_tag|material_item
Override = ["minecraft:bow|minecraft:string", "toolbelt:belt|minecraft:leather"]

